import { JobAdStatusEnum } from '../models/job-ad-status.enum';
import { JobAdDto } from '../models/job-ad.dto';

export const generateId = () => Math.ceil(Math.random() * 1000);
const generateRandomDate = (start: Date, end: Date): Date => {
  return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
};

const today = new Date();
const twoYearsAgo = new Date();
twoYearsAgo.setFullYear(today.getFullYear() - 2);

export let records: JobAdDto[] = [
  {
    id: generateId(),
    title: 'Software Engineer',
    description: 'Join our team to develop cutting-edge software solutions.',
    skills: ['JavaScript', 'React', 'Node.js'],
    status: JobAdStatusEnum.Published,
    createdAt: generateRandomDate(twoYearsAgo, today),
    updatedAt: generateRandomDate(today, new Date()),
    _embedded: {},
  },
  {
    id: generateId(),
    title: 'Graphic Designer',
    description: 'Create stunning visual designs and artwork for our projects.',
    skills: ['Adobe Creative Suite', 'UI/UX Design'],
    status: JobAdStatusEnum.Published,
    createdAt: generateRandomDate(twoYearsAgo, today),
    updatedAt: generateRandomDate(today, new Date()),
    _embedded: {},
  },
  {
    id: generateId(),
    title: 'Marketing Specialist',
    description: 'Drive marketing initiatives and campaigns to boost our brand.',
    skills: ['Social Media Marketing', 'SEO', 'Content Creation'],
    status: JobAdStatusEnum.Published,
    createdAt: generateRandomDate(twoYearsAgo, today),
    updatedAt: generateRandomDate(today, new Date()),
    _embedded: {},
  },
  {
    id: generateId(),
    title: 'Data Analyst',
    description: 'Analyze and interpret complex data sets to derive meaningful insights.',
    skills: ['SQL', 'Python', 'Data Visualization'],
    status: JobAdStatusEnum.Published,
    createdAt: generateRandomDate(twoYearsAgo, today),
    updatedAt: generateRandomDate(today, new Date()),
    _embedded: {},
  },
  {
    id: generateId(),
    title: 'Customer Support Representative',
    description: 'Provide exceptional customer service and support to our clients.',
    skills: ['Communication', 'Problem-Solving', 'Customer Service'],
    status: JobAdStatusEnum.Published,
    createdAt: generateRandomDate(twoYearsAgo, today),
    updatedAt: generateRandomDate(today, new Date()),
    _embedded: {},
  },
  {
    id: generateId(),
    title: 'Project Manager',
    description: 'Lead and coordinate projects to ensure successful delivery.',
    skills: ['Project Management', 'Team Leadership'],
    status: JobAdStatusEnum.Published,
    createdAt: generateRandomDate(twoYearsAgo, today),
    updatedAt: generateRandomDate(today, new Date()),
    _embedded: {},
  },
  {
    id: generateId(),
    title: 'Sales Representative',
    description: 'Drive sales and build relationships with potential clients.',
    skills: ['Sales', 'Negotiation', 'Communication'],
    status: JobAdStatusEnum.Published,
    createdAt: generateRandomDate(twoYearsAgo, today),
    updatedAt: generateRandomDate(today, new Date()),
    _embedded: {},
  },
  {
    id: generateId(),
    title: 'Content Writer',
    description: 'Create compelling and engaging content for various platforms.',
    skills: ['Writing', 'Content Strategy'],
    status: JobAdStatusEnum.Published,
    createdAt: generateRandomDate(twoYearsAgo, today),
    updatedAt: generateRandomDate(today, new Date()),
    _embedded: {},
  },
  {
    id: generateId(),
    title: 'UX/UI Designer',
    description: 'Design intuitive and user-friendly interfaces for our applications.',
    skills: ['UI/UX Design', 'Figma', 'Prototyping'],
    status: JobAdStatusEnum.Published,
    createdAt: generateRandomDate(twoYearsAgo, today),
    updatedAt: generateRandomDate(today, new Date()),
    _embedded: {},
  },
  {
    id: generateId(),
    title: 'DevOps Engineer',
    description: 'Optimize our infrastructure for efficient and scalable deployments.',
    skills: ['DevOps', 'Docker', 'CI/CD'],
    status: JobAdStatusEnum.Published,
    createdAt: generateRandomDate(twoYearsAgo, today),
    updatedAt: generateRandomDate(today, new Date()),
    _embedded: {},
  },
  {
    id: generateId(),
    title: 'HR Manager',
    description: 'Oversee human resources functions and enhance our organizational culture.',
    skills: ['HR Management', 'Recruitment', 'Employee Relations'],
    status: JobAdStatusEnum.Published,
    createdAt: generateRandomDate(twoYearsAgo, today),
    updatedAt: generateRandomDate(today, new Date()),
    _embedded: {},
  },
  {
    id: generateId(),
    title: 'Financial Analyst',
    description: 'Analyze financial data and provide insights for better financial decision-making.',
    skills: ['Financial Analysis', 'Excel', 'Budgeting'],
    status: JobAdStatusEnum.Published,
    createdAt: generateRandomDate(twoYearsAgo, today),
    updatedAt: generateRandomDate(today, new Date()),
    _embedded: {},
  },
  {
    id: generateId(),
    title: 'Content Marketing Manager',
    description: 'Develop and execute content marketing strategies to enhance brand awareness.',
    skills: ['Content Marketing', 'SEO', 'Social Media'],
    status: JobAdStatusEnum.Published,
    createdAt: generateRandomDate(twoYearsAgo, today),
    updatedAt: generateRandomDate(today, new Date()),
    _embedded: {},
  },
  {
    id: generateId(),
    title: 'Cybersecurity Specialist',
    description: 'Ensure the security of our digital assets and mitigate potential risks.',
    skills: ['Cybersecurity', 'Network Security', 'Penetration Testing'],
    status: JobAdStatusEnum.Published,
    createdAt: generateRandomDate(twoYearsAgo, today),
    updatedAt: generateRandomDate(today, new Date()),
    _embedded: {},
  },
  {
    id: generateId(),
    title: 'AI/ML Researcher',
    description: 'Research and develop cutting-edge AI/ML algorithms for innovative applications.',
    skills: ['Machine Learning', 'Python', 'Data Science'],
    status: JobAdStatusEnum.Published,
    createdAt: generateRandomDate(twoYearsAgo, today),
    updatedAt: generateRandomDate(today, new Date()),
    _embedded: {},
  },
];
